
package lt.viko.eif.nlavkart.internetShopClient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountPort", targetNamespace = "www.example.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountPort {


    /**
     * 
     * @param getAccountRequest
     * @return
     *     returns lt.viko.eif.nlavkart.internetShopClient.GetAccountResponse
     */
    @WebMethod
    @WebResult(name = "getAccountResponse", targetNamespace = "generatedsoap", partName = "getAccountResponse")
    public GetAccountResponse getAccount(
        @WebParam(name = "getAccountRequest", targetNamespace = "generatedsoap", partName = "getAccountRequest")
        GetAccountRequest getAccountRequest);

    /**
     * 
     * @param getCartOfAccountRequest
     * @return
     *     returns lt.viko.eif.nlavkart.internetShopClient.GetCartOfAccountResponse
     */
    @WebMethod
    @WebResult(name = "getCartOfAccountResponse", targetNamespace = "generatedsoap", partName = "getCartOfAccountResponse")
    public GetCartOfAccountResponse getCartOfAccount(
        @WebParam(name = "getCartOfAccountRequest", targetNamespace = "generatedsoap", partName = "getCartOfAccountRequest")
        GetCartOfAccountRequest getCartOfAccountRequest);

    /**
     * 
     * @param removeAccountRequest
     * @return
     *     returns lt.viko.eif.nlavkart.internetShopClient.RemoveAccountResponse
     */
    @WebMethod
    @WebResult(name = "removeAccountResponse", targetNamespace = "generatedsoap", partName = "removeAccountResponse")
    public RemoveAccountResponse removeAccount(
        @WebParam(name = "removeAccountRequest", targetNamespace = "generatedsoap", partName = "removeAccountRequest")
        RemoveAccountRequest removeAccountRequest);

    /**
     * 
     * @param getItemFromCartOfAccountRequest
     * @return
     *     returns lt.viko.eif.nlavkart.internetShopClient.GetItemFromCartOfAccountResponse
     */
    @WebMethod
    @WebResult(name = "getItemFromCartOfAccountResponse", targetNamespace = "generatedsoap", partName = "getItemFromCartOfAccountResponse")
    public GetItemFromCartOfAccountResponse getItemFromCartOfAccount(
        @WebParam(name = "getItemFromCartOfAccountRequest", targetNamespace = "generatedsoap", partName = "getItemFromCartOfAccountRequest")
        GetItemFromCartOfAccountRequest getItemFromCartOfAccountRequest);

    /**
     * 
     * @param getAccountsRequest
     * @return
     *     returns lt.viko.eif.nlavkart.internetShopClient.GetAccountsResponse
     */
    @WebMethod
    @WebResult(name = "getAccountsResponse", targetNamespace = "generatedsoap", partName = "getAccountsResponse")
    public GetAccountsResponse getAccounts(
        @WebParam(name = "getAccountsRequest", targetNamespace = "generatedsoap", partName = "getAccountsRequest")
        GetAccountsRequest getAccountsRequest);

    /**
     * 
     * @param createAccountRequest
     * @return
     *     returns lt.viko.eif.nlavkart.internetShopClient.CreateAccountResponse
     */
    @WebMethod
    @WebResult(name = "createAccountResponse", targetNamespace = "generatedsoap", partName = "createAccountResponse")
    public CreateAccountResponse createAccount(
        @WebParam(name = "createAccountRequest", targetNamespace = "generatedsoap", partName = "createAccountRequest")
        CreateAccountRequest createAccountRequest);

}
